export const event = {
  name: "Key Moment",
  yearLabel: "2026–2027",
  title: "Cam kết 2026–2027",
  subtitle: "Ký tên trên điện thoại của bạn",
  pledge:
    "Tôi cam kết đồng hành, đóng góp và lan tỏa tinh thần trách nhiệm trong giai đoạn 2026–2027.",
  signHint: "Ký trong khung bên dưới",
  clearLabel: "Xóa chữ ký",
  confirmLabel: "Xác nhận",
  submittingLabel: "Đang gửi…",
  thanksTitle: "Cảm ơn bạn",
  thanksBody: "Chữ ký của bạn đã được gửi lên màn hình lớn.",
  alreadySignedTitle: "Bạn đã ký",
  alreadySignedBody: "Chữ ký của bạn đang hiển thị trên màn LED.",
  emptySignature: "Hãy ký trước khi xác nhận.",
  missingConfig: "Chưa cấu hình Supabase. Thêm URL và anon key vào .env.local.",
  submitError: "Không gửi được chữ ký. Thử lại giúp bạn.",
  wallError: "Không tải được tường chữ ký. Thử tải lại trang.",
  wallTitle: "Cam kết 2026–2027",
  wallWaiting: "Đang chờ chữ ký…",
  qrTitle: "Quét mã để ký cam kết",
  qrHint: "Mở camera điện thoại và quét mã này",
  qrStaffNote: "Trang dành cho ban tổ chức — chiếu hoặc in mã QR.",
  hubEyebrow: "Điều hướng sự kiện",
  hubTitle: "Key Moment",
  hubSubtitle: "Chọn màn hình bạn đang mở",
  hubAdmin: "Quản lý chữ ký",
  hubAdminHint: "Xem, xóa dữ liệu chữ ký",
  hubSign: "Ký trên điện thoại",
  hubSignHint: "Khách trong hội trường ký cam kết",
  hubLed: "Màn LED",
  hubLedHint: "Mở fullscreen trên màn hình lớn",
  hubQr: "Mã QR cho khách",
  adminTitle: "Quản lý chữ ký",
  adminPinLabel: "Mã PIN ban tổ chức",
  adminPinAction: "Vào quản lý",
  adminPinError: "PIN không đúng.",
  adminCount: "Tổng chữ ký",
  adminEmpty: "Chưa có chữ ký nào.",
  adminDelete: "Xóa",
  adminClear: "Xóa tất cả",
  adminClearConfirm: "Xóa toàn bộ chữ ký?",
  adminOpenLed: "Mở màn LED",
  adminOpenSign: "Trang ký",
  adminOpenQr: "Mã QR",
  adminDownload: "Tải SVG",
  adminDownloadPng: "Tải PNG",
  adminDownloadAll: "Tải tất cả (offline)",
  thanksDownload: "Tải SVG",
  thanksDownloadPng: "Tải PNG",
} as const;

export const SIGNED_STORAGE_KEY = "key-moment-signed-2026-2027";
export const SIGNED_SVG_STORAGE_KEY = "key-moment-signed-svg-2026-2027";
